#!/bin/sh
echo ""
echo "\033[31mPreparing you for Overtone...\033[0m"
echo "\033[31m======================================\033[0m"
echo ""

echo "\033[33mPulling deps...\033[0m"
lein deps

echo ""
echo "\033[33mPulling in Overtone as a checkout for your curious perusal...\033[0m"
git submodule init
git submodule update

echo ""
echo "\033[33mPulling Overtone's deps...\033[0m"
cd checkouts/overtone
lein deps

cd ../overtone-gui
lein deps

echo ""
echo "\033[33mMerging deps...\033[0m"
cp checkouts/overtone-gui/lib/* lib
cp checkouts/overtone/lib/* lib
rm lib/overtone*.jar

echo ""
echo "\033[32m*************************\033[0m"
echo "\033[32m* OK, get your code on! *\033[0m"
echo "\033[32m*************************\033[0m"
echo ""
